import { pipeline } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1";

const MODEL="onnx-community/Qwen2.5-0.5B-Instruct";
let ai=null,loading=true,busy=false,controller=null;
let history=[];
const $=id=>document.getElementById(id);

function resetWelcome(){ $("messages").innerHTML='<div class="welcome"><div class="big-logo">✦</div><h1>How can I help?</h1><p>A faster, more capable local AI assistant. Your conversation stays in this browser.</p><div class="examples"><button>Explain quantum physics simply</button><button>Write a Python game</button><button>Calculate 27 × 48</button><button>What time is it?</button></div></div>';history=[];$("regen").disabled=true;}
function addRow(role,text,typing=false){const row=document.createElement("div");row.className="row "+role;row.innerHTML='<div class="avatar">'+(role==="user"?"Y":"✦")+'</div><div class="bubble"></div>';const b=row.querySelector(".bubble");if(typing)b.innerHTML='<span class="typing"><i></i><i></i><i></i></span>';else render(b,text);$("messages").appendChild(row);$("messages").scrollTop=$("messages").scrollHeight;return b;}
function render(el,text){const safe=text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");const html=safe.replace(/\`\`\`[a-zA-Z0-9]*\n?([\s\S]*?)\`\`\`/g,"<pre>$1</pre>").replace(/\`([^\`]+)\`/g,"<code>$1</code>");el.innerHTML=html;}
function tool(text){let m=text.match(/^\s*(?:calculate|calc)\s+(.+)$/i);if(m){try{if(!/[^0-9+\-*/().%\s]/.test(m[1]))return "Calculator result: "+Function('"use strict";return ('+m[1].replace(/×/g,"*").replace(/÷/g,"/")+')')();}catch{}}if(/what time is it|current time/i.test(text))return "Your local time is "+new Date().toLocaleString()+".";if(/what date is it|today'?s date/i.test(text))return "Today is "+new Date().toLocaleDateString()+".";return null}
async function load(){try{$("modelStatus").textContent="Loading Qwen 0.5B…";$("sideStatus").textContent="Downloading model…";try{if(navigator.gpu){ai=await pipeline("text-generation",MODEL,{device:"webgpu",dtype:"q4"});$("modelStatus").textContent="Qwen 0.5B • WEBGPU";}else{throw new Error("WebGPU unavailable");}}catch(webgpuError){console.warn("WebGPU unavailable, using WASM:",webgpuError);$("modelStatus").textContent="Loading CPU model…";ai=await pipeline("text-generation",MODEL,{device:"wasm",dtype:"q8"});$("modelStatus").textContent="Qwen 0.5B • WASM";}loading=false;$("sideStatus").textContent="Qwen 0.5B • Ready";$("send").disabled=false;}catch(e){console.error("Model load failed:",e);$("modelStatus").textContent="Model failed";$("sideStatus").textContent="Load failed";addRow("assistant","I couldn't load the local AI model. Refresh the page and try again. If it still fails, the browser may be blocking WebGPU or WebAssembly.");}}
async function ask(text){busy=true;controller=new AbortController();$("send").disabled=true;$("stop").hidden=false;$("regen").disabled=true;addRow("user",text);history.push({role:"user",content:text});const local=tool(text);if(local){history.push({role:"assistant",content:local});addRow("assistant",local);finish();return}const b=addRow("assistant","",true);try{const prompt=[{role:"system",content:"You are a capable, friendly AI assistant. Remember the conversation context. Give accurate, useful answers. Use Markdown for code when helpful. Do not claim to be conscious or human."},...history.slice(-10)];const out=await ai(prompt,{max_new_tokens:384,temperature:.65,top_p:.9,do_sample:true,signal:controller.signal});const g=out[0].generated_text;let ans=Array.isArray(g)?g[g.length-1]?.content:"";if(!ans)ans=String(g).trim();b.innerHTML="";render(b,ans);history.push({role:"assistant",content:ans});$("regen").disabled=false}catch(e){if(e.name!=="AbortError"){b.textContent="Generation failed. Try again."}}finally{finish();}}
function finish(){busy=false;controller=null;$("stop").hidden=true;$("send").disabled=loading;}
$("composer").addEventListener("submit",e=>{e.preventDefault();const t=$("input").value.trim();if(t&&!busy&&!loading){$("input").value="";$("input").style.height="auto";ask(t);}});
$("stop").onclick=()=>{if(controller)controller.abort();finish();};
$("clear").onclick=()=>{if(!busy)resetWelcome();};$("newChat").onclick=()=>{if(!busy){resetWelcome();$("input").focus();}};
$("regen").onclick=()=>{if(busy||!ai||!history.length)return;const last=history.findLast(x=>x.role==="user");if(last){history=history.slice(0,-1);const rows=[...document.querySelectorAll(".row")];rows[rows.length-1]?.remove();ask(last.content);}};
$("input").addEventListener("input",e=>{e.target.style.height="auto";e.target.style.height=Math.min(e.target.scrollHeight,180)+"px";});
$("input").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("composer").requestSubmit();}});
$("messages").addEventListener("click",e=>{if(e.target.matches(".examples button")){$("input").value=e.target.textContent;$("input").focus();}});
load();